/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package file.task;

import java.io.File;
import java.io.IOException;
import java.nio.file.FileSystems;
import java.nio.file.Path;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author uko
 */
public class FileTaskUI extends javax.swing.JFrame
{
	
	JFileChooser fileCooser;
	/**
	 * Creates new form FileTaskUI
	 */
	public FileTaskUI()
	{
		initComponents();
	}
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the FileTaskUI Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        srcTextField = new javax.swing.JTextField();
        srcButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tgtTextField = new javax.swing.JTextField();
        tgtButton = new javax.swing.JButton();
        runButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(455, 165));
        setResizable(false);

        jLabel1.setText("Source directory");

        srcTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srcTextFieldActionPerformed(evt);
            }
        });

        srcButton.setText("Choose…");
        srcButton.setToolTipText("");
        srcButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srcButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Target directory");

        tgtTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgtTextFieldActionPerformed(evt);
            }
        });

        tgtButton.setText("Choose…");
        tgtButton.setToolTipText("");
        tgtButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgtButtonActionPerformed(evt);
            }
        });

        runButton.setText("Karamba!");
        runButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel1)
                    .add(layout.createSequentialGroup()
                        .add(srcTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 350, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(srcButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                    .add(jLabel2)
                    .add(layout.createSequentialGroup()
                        .add(tgtTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 350, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(tgtButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 87, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(runButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(srcTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(srcButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(tgtTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(tgtButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .add(18, 18, 18)
                .add(runButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void initFileChooser()
	{
		if(fileCooser == null)
		{
			fileCooser = new JFileChooser();
			fileCooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
		}
	}
	
	private void srcTextFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_srcTextFieldActionPerformed
	{//GEN-HEADEREND:event_srcTextFieldActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_srcTextFieldActionPerformed

	private void srcButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_srcButtonActionPerformed
	{//GEN-HEADEREND:event_srcButtonActionPerformed
		initFileChooser();
		fileCooser.setCurrentDirectory(new File(srcTextField.getText()));
		if (fileCooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION)
		{
			srcTextField.setText(fileCooser.getSelectedFile().getAbsolutePath());
		}
	}//GEN-LAST:event_srcButtonActionPerformed

	private void tgtTextFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_tgtTextFieldActionPerformed
	{//GEN-HEADEREND:event_tgtTextFieldActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_tgtTextFieldActionPerformed

	private void tgtButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_tgtButtonActionPerformed
	{//GEN-HEADEREND:event_tgtButtonActionPerformed
		initFileChooser();
		fileCooser.setCurrentDirectory(new File(tgtTextField.getText()));
		if (fileCooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION)
		{
			tgtTextField.setText(fileCooser.getSelectedFile().getAbsolutePath());
		}
	}//GEN-LAST:event_tgtButtonActionPerformed

	private void runButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_runButtonActionPerformed
	{//GEN-HEADEREND:event_runButtonActionPerformed
		try
		{
			Path srcDir = FileSystems.getDefault().getPath(srcTextField.getText());
			Path tgtDir = FileSystems.getDefault().getPath(tgtTextField.getText());
			file.task.FileTask.cpdirtree(srcDir, tgtDir);
			JOptionPane.showMessageDialog(this, "Done.");
		}
		catch (IOException ex)
		{
			Logger.getLogger(FileTaskUI.class.getName()).log(Level.SEVERE, null, ex);
			JOptionPane.showMessageDialog(this, ex.getLocalizedMessage());
		}
	}//GEN-LAST:event_runButtonActionPerformed
	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[])
	{
		/*
		 * Set the Nimbus look and feel
		 */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try
		{
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
			{
				if ("Nimbus".equals(info.getName()))
				{
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		}
		catch (ClassNotFoundException ex)
		{
			java.util.logging.Logger.getLogger(FileTaskUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		catch (InstantiationException ex)
		{
			java.util.logging.Logger.getLogger(FileTaskUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		catch (IllegalAccessException ex)
		{
			java.util.logging.Logger.getLogger(FileTaskUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		catch (javax.swing.UnsupportedLookAndFeelException ex)
		{
			java.util.logging.Logger.getLogger(FileTaskUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/*
		 * Create and display the form
		 */
		java.awt.EventQueue.invokeLater(new Runnable()
		{
			@Override
			public void run()
			{
				new FileTaskUI().setVisible(true);
			}
		});
	}

	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton runButton;
    private javax.swing.JButton srcButton;
    private javax.swing.JTextField srcTextField;
    private javax.swing.JButton tgtButton;
    private javax.swing.JTextField tgtTextField;
    // End of variables declaration//GEN-END:variables
}
